name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare pnpm
        uses: pnpm/action-setup@v2

      - name: Prepare Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: ESLint
        run: pnpm run eslint

      - name: Prettier code style check
        run: pnpm prettier . --check

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Publish (development)
        if: github.repository == 'RightCapitalHQ/phpdoc-parser' && github.base_ref == github.event.repository.default_branch
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
          preid=$(sed -e s:/:-:g <<<${{ github.head_ref }}).${{ github.run_number }}
          npm --no-git-tag-version version prerelease --preid="${preid}"
          pnpm publish --no-git-checks --access public --tag development

      - name: Publish (main)
        if: github.repository == 'RightCapitalHQ/phpdoc-parser' && github.ref_name == github.event.repository.default_branch
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
          pnpm beachball publish --yes -m 'chore(release): applying package updates'
