name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]

  workflow_dispatch:
    inputs:
      prerelease:
        required: true
        type: boolean
      branch_name:
        required: true
        type: string
      run_number:
        required: true
        type: string
      run_attempt:
        required: true
        type: string

jobs:
  release:
    if: >-
      github.event_name == 'pull_request'
      && github.event.pull_request.merged == true
      && github.event.pull_request.head.ref == 'release'
    uses: RightCapitalHQ/actions/.github/workflows/nx-release.yml@nx-release/v0.4.2
    with:
      publish: true
    secrets: inherit

  prerelease:
    if: inputs.prerelease
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch_name }}
          persist-credentials: false
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install

      - name: Publish prerelease (development)
        env:
          BRANCH_NAME: ${{ inputs.branch_name }}
          RUN_NUMBER: ${{ inputs.run_number }}
          RUN_ATTEMPT: ${{ inputs.run_attempt }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          preid="${BRANCH_NAME//\//-}".${RUN_NUMBER}.${RUN_ATTEMPT}
          npm --no-git-tag-version version prerelease --preid="${preid}"
          pnpm publish --no-git-checks --access public --tag development
